# Generated by Django 5.2.2 on 2025-12-10 11:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Video', 'Video'), ('Image', 'Image'), ('Iframe', 'Iframe'), ('other', 'Other')], max_length=200)),
                ('file', models.FileField(unique=True, upload_to='')),
                ('file_url', models.TextField(blank=True, null=True)),
                ('file_uuid', models.UUIDField(null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nationality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, unique=True)),
                ('slug', models.SlugField(null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('cartegory', models.CharField(choices=[('Business', 'Business'), ('Entertainments', 'Entertainment'), ('Sport', 'Sport'), ('Education', 'Education'), ('Social', 'Social'), ('Programming', 'Programming'), ('Technology', 'Technology'), ('Tools', 'Tools'), ('Marketing', 'Marketing'), ('News', 'News'), ('Finance', 'Finance'), ('Health', 'Health'), ('Travel', 'Travel'), ('Food', 'Food'), ('Lifestyle', 'Lifestyle'), ('Music', 'Music'), ('Movies', 'Movies'), ('Science', 'Science'), ('Politics', 'Politics'), ('Environment', 'Environment'), ('Fashion', 'Fashion'), ('Gaming', 'Gaming'), ('Art', 'Art'), ('History', 'History'), ('Culture', 'Culture'), ('Religion', 'Religion'), ('Philosophy', 'Philosophy'), ('Psychology', 'Psychology'), ('Self-Help', 'Self-Help'), ('Relationships', 'Relationships'), ('Parenting', 'Parenting'), ('Pets', 'Pets'), ('Automotive', 'Automotive'), ('Real Estate', 'Real Estate'), ('Legal', 'Legal'), ('Human Resources', 'Human Resources'), ('Economics', 'Economics'), ('Cryptocurrency', 'Cryptocurrency'), ('Blockchain', 'Blockchain'), ('Artificial Intelligence', 'Artificial Intelligence'), ('Machine Learning', 'Machine Learning'), ('Data Science', 'Data Science')], max_length=200, null=True)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('post_uuid', models.UUIDField(null=True, unique=True)),
                ('reads', models.BigIntegerField(default=0)),
                ('is_published', models.BooleanField(default=False)),
                ('is_edited', models.BooleanField(default=False)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='PostAuthor', to=settings.AUTH_USER_MODEL)),
                ('post_file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Post_file', to='nijablog.articlefile')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Region', to='nijablog.nationality')),
                ('tags', models.ManyToManyField(related_name='PostTags', to='nijablog.tag')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
